from dataclasses import dataclass
@dataclass(slots=True)
class TrustEvidenceError(Exception):
    code: str; message: str
    def __str__(self): return f"{self.code}: {self.message}"
SCHEMA_VALIDATION="TE-E-SCHEMA_VALIDATION"; CANONICAL_SERIALISATION="TE-E-CANONICAL_SERIALISATION"; DOMAIN_TAG_MISMATCH="TE-E-DOMAIN_TAG_MISMATCH"; UNAUTHORISED_SIGNER="TE-E-UNAUTHORISED_SIGNER"; WRONG_BACKEND_IDENTITY="TE-E-WRONG_BACKEND_IDENTITY"; WRONG_LOG_IDENTITY="TE-E-WRONG_LOG_IDENTITY"; STALE_CHECKPOINT="TE-E-STALE_CHECKPOINT"; ROLLBACK_DETECTED="TE-E-ROLLBACK_DETECTED"; FORK_EVIDENCE="TE-E-FORK_EVIDENCE"; MISSING_WITNESS="TE-E-MISSING_WITNESS"; UNSATISFIED_FINALITY="TE-E-UNSATISFIED_FINALITY"; UNAVAILABLE_PROOF="TE-E-UNAVAILABLE_PROOF"; VERIFIER_STATE_LOSS="TE-E-VERIFIER_STATE_LOSS"; PRE_BOUNDARY_NON_EMISSION="TE-E-PRE_BOUNDARY_NON_EMISSION"; DUPLICATE_EMISSION="TE-E-DUPLICATE_EMISSION"
