"""Stable validation error taxonomy."""

from __future__ import annotations

from dataclasses import dataclass

SCHEMA_REQUIRED = "TE-E-SCHEMA-REQUIRED"
SCHEMA_ADDITIONAL = "TE-E-SCHEMA-ADDITIONAL"
SCHEMA_BRANCH = "TE-E-SCHEMA-BRANCH"
SCHEMA_VALUE = "TE-E-SCHEMA-VALUE"
TIMESTAMP_FORMAT = "TE-E-TIMESTAMP-FORMAT"
TIMESTAMP_ORDER = "TE-E-TIMESTAMP-ORDER"
MIN_PAYLOAD = "TE-E-MIN-PAYLOAD"
MIN_IDENTIFIER = "TE-E-MIN-IDENTIFIER"
MIN_INFRA = "TE-E-MIN-INFRA"
CONSENT_STATE = "TE-E-CONSENT-STATE"
PROVENANCE_LINK = "TE-E-PROVENANCE-LINK"
AGGREGATION_WINDOW = "TE-E-AGGREGATION-WINDOW"
AGGREGATION_COUNT = "TE-E-AGGREGATION-COUNT"
OBJECT_ROLE = "TE-E-OBJECT-ROLE"
OBJECT_DUPLICATE = "TE-E-OBJECT-DUPLICATE"
SUBJECT_CONSISTENCY = "TE-E-SUBJECT-CONSISTENCY"
RECEIPT_STRUCTURE = "TE-E-RECEIPT-STRUCTURE"
FAILURE_OUTPUT = "TE-E-FAILURE-OUTPUT"
PAYLOAD_BINDING = "TE-E-PAYLOAD-BINDING"
CURATION_RESULT = "TE-E-CURATION-RESULT"


@dataclass(frozen=True, slots=True)
class ValidationIssue:
    code: str
    path: str
    message: str
    layer: str


class ValidationFailure(ValueError):
    """Raised by strict helpers when a validation result is not accepted."""

    def __init__(self, issue: ValidationIssue):
        super().__init__(f"{issue.code} at {issue.path}: {issue.message}")
        self.issue = issue

CANONICALISATION = "TE-E-CANONICALISATION"
CORE_SIGNATURE = "TE-E-CORE-SIGNATURE"
RECEIPT_SIGNATURE = "TE-E-RECEIPT-SIGNATURE"
RECEIPT_BINDING = "TE-E-RECEIPT-BINDING"
PROOF_DIGEST = "TE-E-PROOF-DIGEST"
PROOF_INDEX = "TE-E-PROOF-INDEX"
PROOF_SIZE = "TE-E-PROOF-SIZE"
PROOF_PATH = "TE-E-PROOF-PATH"
LEAF_BINDING = "TE-E-LEAF-BINDING"
BACKEND_IDENTITY = "TE-E-BACKEND-IDENTITY"
LOG_IDENTITY = "TE-E-LOG-IDENTITY"
CHECKPOINT_ROLLBACK = "TE-E-CHECKPOINT-ROLLBACK"
CHECKPOINT_FORK = "TE-E-CHECKPOINT-FORK"
CHECKPOINT_IDENTITY = "TE-E-CHECKPOINT-IDENTITY"
PAYLOAD_COMMITMENT = "TE-E-PAYLOAD-COMMITMENT"
CONSISTENCY_MISSING = "TE-E-CONSISTENCY-MISSING"
CONSISTENCY_STRUCTURE = "TE-E-CONSISTENCY-STRUCTURE"
CONSISTENCY_IDENTITY = "TE-E-CONSISTENCY-IDENTITY"
CONSISTENCY_SIZE = "TE-E-CONSISTENCY-SIZE"
CONSISTENCY_ROOT = "TE-E-CONSISTENCY-ROOT"
CONSISTENCY_PATH = "TE-E-CONSISTENCY-PATH"
