id: te.trustevidence
canonical: https://example.org/fhir/te
name: TrustEvidenceAuditBoundary
title: TrustEvidence Audit Boundary Draft IG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: local-validation-draft
publisher:
  name: TrustEvidence research artefact
  url: https://github.com/antonioclim/TEA-Sim
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
dependencies:
  ihe.iti.balp: 1.1.4
parameters:
  show-inherited-invariants: false
  path-expansion-params: '../../exp-params.json'
