name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  local-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -e '.[test]'
      - run: make ci-local
      - run: make experiments
      - run: make validate-results
      - run: make analyse-results
  fsh-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: make validate-fsh-static
      - run: make sushi-build
        continue-on-error: true
